# Generated by Django 5.2 on 2025-04-17 21:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('tagline', models.CharField(max_length=50, verbose_name='Tagline')),
                ('organization', models.CharField(max_length=50, verbose_name='Organization')),
                ('rank', models.CharField(max_length=50, verbose_name='Rank')),
                ('interested', models.IntegerField(blank=True, default=0, null=True, verbose_name='Interested')),
                ('interesting', models.IntegerField(blank=True, default=0, null=True, verbose_name='Interesting')),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.image_upload, verbose_name='Profile Image')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=accounts.models.image_upload, verbose_name='Profile Cover')),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Profile Views')),
                ('discussions_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Discussions Count')),
                ('discussions_interacted_with', models.IntegerField(blank=True, default=0, null=True, verbose_name='Discussions Interacted With')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
