# Generated by Django 5.2 on 2025-04-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='forums_tags',
            field=models.ManyToManyField(to='social.tag'),
        ),
    ]
