# Generated by Django 5.2 on 2025-04-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_forums_tags'),
        ('social', '0002_alter_discussion_interested_alter_forum_discussions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='forums_tags',
            field=models.ManyToManyField(null=True, to='social.tag'),
        ),
    ]
