# Generated by Django 5.2 on 2025-04-17 21:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.cover_upload, verbose_name='Profile Cover'),
        ),
    ]
