# Generated by Django 5.0.1 on 2025-04-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_name_alter_profile_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='user', max_length=50, null=True, verbose_name='Name'),
        ),
    ]
