# Generated by Django 5.2 on 2025-05-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='forums_tags',
        ),
    ]
