name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  dotted_border: ^2.0.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.0
  flutter_neumorphic: ^3.2.0
  image_picker: ^0.8.7+4
  permission_handler: ^10.2.0
  file_picker: ^10.1.8
  http: ^1.3.0
  cupertino_icons: ^1.0.6
  provider: ^6.1.5
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
