# Generated by Django 5.2 on 2025-04-17 21:33

import django.db.models.deletion
import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('created_on', models.DateField(auto_now=True, verbose_name='Creation Date')),
                ('interested_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Interested Count')),
                ('comments_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Comments Count')),
                ('interested', models.ManyToManyField(blank=True, null=True, related_name='interested_profiles', to='accounts.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_owner', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Discussion',
                'verbose_name_plural': 'Discussions',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('created_on', models.DateField(auto_now=True, verbose_name='Creation Date')),
                ('ups', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ups')),
                ('downs', models.IntegerField(blank=True, default=0, null=True, verbose_name='Downs')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to='accounts.profile')),
                ('discussion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interested_profiles', to='social.discussion')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=social.models.image_upload, verbose_name='Forum Cover')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('created_on', models.DateField(auto_now=True, verbose_name='Creation Date')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('members_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Members Count')),
                ('discussions', models.ManyToManyField(blank=True, null=True, to='social.discussion')),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='forum_members', to='accounts.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_owner', to='accounts.profile')),
                ('tags', models.ManyToManyField(to='social.tag')),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forums',
            },
        ),
    ]
