# Generated by Django 5.2 on 2025-04-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_forums_tags'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='interested',
            field=models.ManyToManyField(related_name='interested_profiles', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='discussions',
            field=models.ManyToManyField(to='social.discussion'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='members',
            field=models.ManyToManyField(related_name='forum_members', to='accounts.profile'),
        ),
    ]
