# Generated by Django 5.0.1 on 2025-04-18 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_comment_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='discussions',
        ),
        migrations.AddField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='social.forum'),
        ),
    ]
