# Generated by Django 5.0.1 on 2025-04-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_name'),
        ('social', '0004_remove_forum_discussions_discussion_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='interested',
            field=models.ManyToManyField(blank=True, null=True, related_name='interested_profiles', to='accounts.profile'),
        ),
    ]
