# Generated by Django 5.0.1 on 2025-04-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_name'),
        ('social', '0005_alter_discussion_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downers',
            field=models.ManyToManyField(related_name='comment_downers', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='uppers',
            field=models.ManyToManyField(related_name='comment_uppers', to='accounts.profile'),
        ),
    ]
