# Generated by Django 5.0.1 on 2025-04-18 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_comment_downers_comment_uppers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.discussion'),
        ),
    ]
