# Generated by Django 5.2 on 2025-05-15 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_forums_tags'),
        ('social', '0007_alter_comment_discussion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='profile',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forum',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='downers',
            field=models.ManyToManyField(related_name='comment_downers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='uppers',
            field=models.ManyToManyField(related_name='comment_uppers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='interested',
            field=models.ManyToManyField(blank=True, null=True, related_name='interested_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='forum_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
