# Generated by Django 5.2 on 2025-05-15 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_forums_tags'),
        ('social', '0008_remove_forum_tags_remove_comment_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_owner', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='forum',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_owner', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='downers',
            field=models.ManyToManyField(related_name='comment_downers', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='uppers',
            field=models.ManyToManyField(related_name='comment_uppers', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='interested',
            field=models.ManyToManyField(blank=True, null=True, related_name='interested_profiles', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='forum_members', to='accounts.profile'),
        ),
    ]
